import ReactPDF, {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";
import React from "react";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#1a1a1a",
    paddingBottom: 10,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  description: {
    fontSize: 10,
    color: "#666",
  },
  fieldRow: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 8,
  },
  fieldLabel: {
    fontSize: 9,
    color: "#666",
    marginBottom: 2,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  fieldValue: {
    fontSize: 12,
  },
  signatureImage: {
    width: 200,
    height: 80,
    objectFit: "contain",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 8,
  },
  respondentInfo: {
    marginBottom: 16,
    padding: 10,
    backgroundColor: "#f8f8f8",
    borderRadius: 4,
  },
  respondentText: {
    fontSize: 10,
    marginBottom: 2,
  },
});

interface SubmissionField {
  label: string;
  value: string;
  type: string;
}

interface SubmissionPDFProps {
  title: string;
  description?: string;
  respondentName: string;
  respondentEmail: string;
  fields: SubmissionField[];
  submittedAt: string;
}

function SubmissionPDF({
  title,
  description,
  respondentName,
  respondentEmail,
  fields,
  submittedAt,
}: SubmissionPDFProps) {
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, title),
        description
          ? React.createElement(Text, { style: styles.description }, description)
          : null
      ),
      React.createElement(
        View,
        { style: styles.respondentInfo },
        React.createElement(
          Text,
          { style: styles.respondentText },
          `Submitted by: ${respondentName}`
        ),
        React.createElement(
          Text,
          { style: styles.respondentText },
          `Email: ${respondentEmail}`
        ),
        React.createElement(
          Text,
          { style: styles.respondentText },
          `Date: ${new Date(submittedAt).toLocaleString()}`
        )
      ),
      ...fields.map((field, i) =>
        React.createElement(
          View,
          { key: i, style: styles.fieldRow },
          React.createElement(Text, { style: styles.fieldLabel }, field.label),
          field.type === "signature" && field.value
            ? React.createElement(Image, {
                style: styles.signatureImage,
                src: field.value,
              })
            : React.createElement(
                Text,
                { style: styles.fieldValue },
                field.value || "—"
              )
        )
      ),
      React.createElement(
        View,
        { style: styles.footer },
        React.createElement(
          Text,
          null,
          `Generated by Form Beast • ${new Date(submittedAt).toLocaleString()}`
        )
      )
    )
  );
}

export async function generateSubmissionPDF(
  props: SubmissionPDFProps
): Promise<Buffer> {
  const element = React.createElement(SubmissionPDF, props);
  const stream = await ReactPDF.renderToStream(element);

  const chunks: Uint8Array[] = [];
  for await (const chunk of stream) {
    chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk);
  }

  return Buffer.concat(chunks);
}
